version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5001:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/venv # Lokaldeki venv klasörünü izole et

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    environment:
      - VITE_API_BASE_URL=http://localhost:5001
    volumes:
      - ./frontend:/app
      - /app/node_modules # Lokaldeki node_modules'ü izole et
    depends_on:
      - backend
